export enum ExifKey {
  "Make" = "Make",
  "Model" = "Model",
  "XResolution" = "XResolution",
  "YResolution" = "YResolution",
  "ResolutionUnit" = "ResolutionUnit",
  "Software" = "Software",
  "ModifyDate" = "ModifyDate",
  "ExposureTime" = "ExposureTime",
  "FNumber" = "FNumber",
  "ExposureProgram" = "ExposureProgram",
  "ISO" = "ISO",
  "ExifVersion" = "ExifVersion",
  "DateTimeOriginal" = "DateTimeOriginal",
  "CreateDate" = "CreateDate",
  "OffsetTime" = "OffsetTime",
  "OffsetTimeOriginal" = "OffsetTimeOriginal",
  "OffsetTimeDigitized" = "OffsetTimeDigitized",
  "ShutterSpeedValue" = "ShutterSpeedValue",
  "ApertureValue" = "ApertureValue",
  "ExposureCompensation" = "ExposureCompensation",
  "MaxApertureValue" = "MaxApertureValue",
  "MeteringMode" = "MeteringMode",
  "LightSource" = "LightSource",
  "Flash" = "Flash",
  "FocalLength" = "FocalLength",
  "SubSecTimeOriginal" = "SubSecTimeOriginal",
  "SubSecTimeDigitized" = "SubSecTimeDigitized",
  "ColorSpace" = "ColorSpace",
  "FocalPlaneXResolution" = "FocalPlaneXResolution",
  "FocalPlaneYResolution" = "FocalPlaneYResolution",
  "FocalPlaneResolutionUnit" = "FocalPlaneResolutionUnit",
  "SensingMethod" = "SensingMethod",
  "FileSource" = "FileSource",
  "SceneType" = "SceneType",
  "CustomRendered" = "CustomRendered",
  "ExposureMode" = "ExposureMode",
  "WhiteBalance" = "WhiteBalance",
  "DigitalZoomRatio" = "DigitalZoomRatio",
  "FocalLengthIn35mmFormat" = "FocalLengthIn35mmFormat",
  "SceneCaptureType" = "SceneCaptureType",
  "GainControl" = "GainControl",
  "Contrast" = "Contrast",
  "Saturation" = "Saturation",
  "Sharpness" = "Sharpness",
  "SerialNumber" = "SerialNumber",
  "LensModel" = "LensModel",
  "LensSerialNumber" = "LensSerialNumber",
}

export const ExifKeyName = {
  Make: "厂商",
  Model: "型号",
  XResolution: "X分辨率",
  YResolution: "Y分辨率",
  ResolutionUnit: "分辨率单位",
  Software: "软件",
  ModifyDate: "修改时间",
  ExposureTime: "曝光时间",
  FNumber: "光圈值",
  ExposureProgram: "曝光程序",
  ISO: "ISO",
  ExifVersion: "Exif版本",
  DateTimeOriginal: "拍摄时间",
  CreateDate: "创建时间",
  OffsetTime: "偏移时间",
  OffsetTimeOriginal: "偏移时间",
  OffsetTimeDigitized: "偏移时间",
  ShutterSpeedValue: "快门速度",
  ExposureCompensation: "曝光补偿",
  MaxApertureValue: "最大光圈值",
  MeteringMode: "测光模式",
  LightSource: "光源",
  Flash: "闪光灯",
  FocalLength: "焦距",
  ColorSpace: "色彩空间",
  ExposureMode: "曝光模式",
  WhiteBalance: "白平衡",
  FocalLengthIn35mmFormat: "35mm等效焦距",
  Contrast: "对比度",
  Saturation: "饱和度",
  Sharpness: "锐度",
  SerialNumber: "序列号",
  LensModel: "镜头型号",
  LensSerialNumber: "镜头序列号",
};
